<table class="table" id="usecase-content">
<tr>
    <th>
        Cas d'utilisation
    </th>
    <th>
        Poids
    </th>
    <th>
        Progression
    </th>
    <th>
        Tâches
    </th>
</tr>
    <?php
        foreach($usecase as $case){
            ?>
                <tr class="usecase" data-show="<?php echo $case->code; ?>">
                    <td>
                        <?php echo $case->nom; ?>
                    </td>
                    <td>
                        <?php echo $case->poids; ?>
                    </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="<?php echo $case->getAvancementByAuthor($case->idDev); ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $case->getAvancementByAuthor($case->idDev); ?>%">
                                <?php echo round($case->getAvancementByAuthor($case->idDev)) . " %"; ?>
                            </div>
                        </div>
                    </td>
                    <td>
                        <?php echo count($case->tache); ?> tâches
                    </td>
                </tr>
                <tr class="usecase-hide hide" id="usecase_show_<?php echo $case->code; ?>">
                    <td colspan="4">
                        <table class="table" id="usecase_<?php echo $case->code; ?>"">
                        </table>
                    </td>
                </tr>
            <?php
        }
    ?>
</table>