<div class="row">
    <div class="col-sm-3">

    </div>
    <div class="col-sm-9">
        <div class="alert alert-success title">
            <?php echo $projet->nom . " [" . $projet->user->identite . "]";?>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Détails du projet</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p class="form-control"><?php echo $projet->description ?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <p class="form-control"><?php echo $projet->dateLancement ?></p>
                    </div>
                    <div class="col-sm-3">
                        <p class="form-control"><?php echo $projet->dateFinPrevue ?></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Equipe</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <?php /*
                    foreach($projet->usecase as $usecase){
                        echo "<tr><td>" . $usecase->user->identite . " [$usecase->poids]</td></tr>";
                    } */
                    ?>
                </table>
            </div>
        </div>

    </div>
</div>