<?php
if(!$user  || !$user->getAuthorProject()){
    return;//TODO: redirection vers une page 404
}
?>
<div class="row">
    <!-- Affichage du nom de l'utilisateur -->
    <div class="col-sm-12">
        <div class="alert alert-success title">
        <span class="glyphicon glyphicon-user"></span><?php echo " " . $user->identite;?> /Mes Projets:
        </div>
    </div>
</div>
        <?php
        /*
         * On boucle pour afficher la liste des projets de l'utilisateur
         */
            foreach($user->getAuthorProject() as $projet) {
                ?>
                <div class="row projet">
                    <div class="col-sm-2">
                        <!-- Affichage du nom du projet -->
                        <?php echo $projet->nom ?>
                    </div>
                    <div class="col-sm-6">
                        <?php
                        /*
                         * On boucle pour récupéré le pourcentage d'avancement total
                         * à partir des cas d'utilisations
                         */
                            $avancement = 0;
                            for($j=0 ; $j<count($projet->usecase) ; $j++) {
                                $avancement = $avancement + $projet->usecase[$j]->getAvancement();
                            }
                        /*
                         * On vérifie ou en est le projet et on selon son retard les couleurs changent
                         */
                            $notificationAvancement = "success";
                            if($projet->getJourRestant() < 0){
                                $notificationAvancement = "danger";
                            }elseif($avancement < $projet->getPourcentageTempEcoule()){
                                $notificationAvancement = "warning";
                            }
                        ?>
                        <!-- Affichage de la progressBar -->
                        <div class="progress">
                            <div class="progress-bar progress-bar-<?php echo $notificationAvancement; ?> progress-bar-striped" role="progressbar" aria-valuenow="<?php echo $avancement; ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $avancement; ?>%">
                                <?php echo round($avancement) . " %"; ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <!-- Affichage du nombre de jours restants -->
                        <?php echo $projet->getJourRestant() . " Jours restant" ?>
                    </div>
                    <div class="col-sm-2">
                        <button data-href="<?php echo $projet->id;?>" class="btn btn-default">Ouvrir...</button>
                    </div>
                </div>
            <?php
            }

        ?>
</div>
<?=$script_foot?>