<div class="row">
    <div class="col-sm-3">
        <!-- IMAGE HERE -->
    </div>
    <div class="col-sm-9">
        <div class="alert alert-success title">
            <?php echo $projet->nom . " [" . $projet->user->identite . "]";?>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Détails du projet</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p class="well"><?php echo $projet->description ?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <p class="form-control"><?php echo $projet->dateLancement ?></p>
                    </div>
                    <div class="col-sm-3">
                        <p class="form-control"><?php echo $projet->dateFinPrevue ?></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Mes Uses Cases</h3>
            </div>
            <div class="panel-body" id="usecase-content">
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-sm-4 col-sm-offset-3">
        <button style="width: 100%;" class="btn btn-default" id="btnMessages"><?php echo count($projet->message); ?> Messages...</button>
    </div>
</div>
<div class="row">
    <div class="col-sm-9 col-sm-offset-3" id="divMessages">

    </div>
</div>
<div class="row">
    <div class="col-sm-offset-3 col-sm-9">
        <button class="btn btn-default" data-user="<?php echo $projet->idClient; ?>" id="btnReturn">Fermer le Projet</button>
    </div>
</div>

<?=$script_foot?>